---
title: "NBC 16s Analyses.`r format(Sys.time(), '%d %B, %Y')`"
author: "Sam Dunn"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r Load Data, include=FALSE,echo=FALSE,warning=FALSE}
rm(list = ls(all = TRUE))
algae.df<- read.delim("C:/Users/sdunn3/Google Drive/North Branch Chicago Data/NBC/nbc23s.final.subsample.tax.summary")


library(vegan)
library(RAM)
library(tidyr)
library(Rmisc)
library(reshape)
library(reshape2)
#source('http://bioconductor.org/biocLite.R')
#biocLite('phyloseq')
#library(phyloseq)
library(tidyr)
library(gapminder)
library(magrittr)
library(dplyr)
library(ggpubr)
library(gridExtra)
library(patternplot)
library(tibble)
#devtools::install_github("timelyportfolio/sunburstR")
library(sunburstR)
library(broom)
library(data.table)
library(devtools)
library(gdata)
install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
library(pairwiseAdonis)
#bacteria.df=subset.data.frame(bacteria.df, taxlevel=3) #select for genus level sequences
theme_set(theme_gray(base_size = 18))
pd=position_dodge(width=0.4)

#design.file.23=as.data.frame(colnames(algae.df))
#design.file.23=as.data.frame(design.file.23)
#design.file.23=t(design.file.23)
#design.file.23=as.data.frame(design.file.23)

#design.file.23=separate(design.file.23,'colnames(algae.df)',into=c("x","Group"),sep=c(1))
#design.file.23$x=NULL
#design.file.23=separate(design.file.23,Group,into=c("Date","Substrate"),sep=c(6),remove=FALSE)
#design.file.23=separate(design.file.23,Substrate,into=c("Substrate","Rep"),sep=c(-1))
#write.table(design.file,file="NBC_design_23.txt",sep="\t")



```

```{r}

shannon<-function(x){
  shan.list=diversity(x,index="shannon")
  return(shan.list)
}


shannon.nbc=apply(algae.df[,6:71],2,shannon)



list_to_df <- function(list_for_df) {
  list_for_df <- as.list(list_for_df)

  nm <- names(list_for_df)
  if (is.null(nm))
    nm <- seq_along(list_for_df)

  df <- data.frame(name = nm, stringsAsFactors = FALSE)
  df$value <- unname(list_for_df)
  df
}

shannon.df=list_to_df(shannon.nbc)
shannon.df$value=as.numeric(shannon.df$value)
shannon.df$pielou=shannon.df$value/log(202685)



shannon.df=separate(shannon.df,name,into=c("junk","Date","Substrate"),sep=c(1,7))
shannon.df=separate(shannon.df,Substrate,into=c("Substrate","Rep"),sep=c(-1))
shannon.df$junk=NULL
shannon.df=droplevels(shannon.df[-which(shannon.df$Substrate=='CR'),])
shannon.df$Date=as.factor(shannon.df$Date)
shannon.df$Date=revalue(shannon.df$Date,c("170818"="3","170828"="10","170905"="21","170915"="31"))

shannon.div.summary=summarySE(shannon.df,measurevar="value",groupvars=c("Date","Substrate"),na.rm=TRUE)
shannon.even.summary=summarySE(shannon.df,measurevar="pielou",groupvars=c("Date","Substrate"),na.rm=TRUE)

shannon.div=ggplot(shannon.div.summary, aes(x=Date,y=value,group=Substrate,shape=Substrate,fill=Substrate))+
  geom_point(position=pd,size=4)+geom_line(aes(linetype=Substrate),position=pd)+
  geom_errorbar(aes(ymin=value-se,ymax=value+se),width=0.3,position=pd)+ylab("Shannon Diversity (H')")+
  theme_classic()+
  theme(legend.position=c(0.25,0.95),
        legend.title=element_blank(),
        legend.direction="horizontal",
        axis.text=element_text(size=16),
        axis.title=element_text(size=16),
        legend.text=element_text(size=14))+
  scale_shape_manual(name="Substrate",values=c(21,22,23,24,25,26))
shannon.div


#geom_bar(stat="identity",position=position_dodge(0.9))+

#,position=position_dodge(0.9)
```

```{r}
shannon.even=ggplot(shannon.even.summary, aes(x=Date,y=pielou,group=Substrate,shape=Substrate,fill=Substrate))+
  geom_point(position=pd,size=4)+geom_line(aes(linetype=Substrate),position=pd)+
  geom_errorbar(aes(ymin=pielou-se,ymax=pielou+se),width=0.3,position=pd)+ylab("Pielou's Evenness")+
  theme_classic()+
  theme(legend.position=c(0.25,0.95),legend.title=element_blank(),legend.direction="horizontal",
        axis.text=element_text(size=16),
        axis.title=element_text(size=16),
        legend.text=element_text(size=14))+
  scale_shape_manual(name="Substrate",values=c(21,22,23,24,25,26))
shannon.even
```
```{r}
algae.df$taxlevel=as.factor(algae.df$taxlevel)
algae.df.6=subset.data.frame(algae.df, taxlevel==6,drop=TRUE)
observationThreshold = 1
otu=apply(algae.df.6[,6:71]>=observationThreshold, 2, sum,na.rm=T)
otu.0=apply(algae.df.6[,6:71],2,sum,na.rm=T)

list_to_df <- function(list_for_df) {
  list_for_df <- as.list(list_for_df)

  nm <- names(list_for_df)
  if (is.null(nm))
    nm <- seq_along(list_for_df)

  df <- data.frame(name = nm, stringsAsFactors = FALSE)
  df$value <- unname(list_for_df)
  df
}

otu.df=list_to_df(otu)
otu.df$value=as.numeric(otu.df$value)
otu.df=separate(otu.df,name,into=c("junk","Date","Substrate"),sep=c(1,7))
otu.df=separate(otu.df,Substrate,into=c("Substrate","Rep"),sep=c(-1))
otu.df$junk=NULL
otu.df=droplevels(otu.df[-which(otu.df$Substrate=='CR'),])
otu.df$Date=as.factor(otu.df$Date)
otu.df$Date=revalue(otu.df$Date,c("170818"="3","170828"="10","170905"="21","170915"="31"))

out.aov=otu.df%>%
  group_by(Date)%>%
  do(tidy(aov(value~Substrate,data=.)))
out.aov

tukey.out=otu.df%>%
  group_by(Date)%>%
  do(multitst=TukeyHSD(aov(value~Substrate,data=.)))
tukey.out %>%tidy(multitst)



otu.df.summary=summarySE(otu.df,measurevar="value",groupvars=c("Date","Substrate"),na.rm=TRUE)

pd=position_dodge(width=0.4)
otu.plot=ggplot(otu.df.summary, aes(x=Date,y=value,group=Substrate,shape=Substrate,fill=Substrate))+
  geom_point(position=pd,size=4)+geom_line(aes(linetype=Substrate),position=pd)+
  geom_errorbar(aes(ymin=value-se,ymax=value+se),width=0.3,position=pd)+
  ylab("Observed OTUs")+
  theme_classic()+
  theme(legend.position=c(0.25,0.95),
        legend.title=element_blank(),
        legend.direction="horizontal",
        axis.text=element_text(size=16),
        axis.title=element_text(size=16),
        legend.text=element_text(size=14))+
  scale_shape_manual(name="Substrate",values=c(21,22,23,24,25,26))
otu.plot
```

```{r}

theme_set(theme_classic(base_size = 18))
algae.df.3=subset.data.frame(algae.df, taxlevel==3,drop=TRUE)

sites=list(colnames(algae.df.3[,6:71])) #get list of samples
total=list(colnames(algae.df.3[,1]))


rabund=function(sites){
  rabund=sites/algae.df.3$total
  return(rabund)
}

rabund.df=rabund(algae.df.3[,6:71])
rabund.df=cbind(algae.df.3$taxon,rabund.df)



rabund.df=dcast(melt(rabund.df,id.vars="algae.df.3$taxon"),variable~algae.df.3$taxon)
#rabund.df$variable=as.numeric(rabund.df$variable)
rabund.df=separate(rabund.df,variable,into=c("junk","Date","Substrate"),sep=c(1,7))
rabund.df=separate(rabund.df,Substrate,into=c("Substrate","Rep"),sep=c(-1))
rabund.df$junk=NULL

rabund.df=droplevels(rabund.df[-which(rabund.df$Substrate=='CR'),])
rabund.df$Date=as.factor(rabund.df$Date)
rabund.df$Date=revalue(rabund.df$Date,c("170818"="3","170828"="10","170905"="21","170915"="31"))
#rabund.df$Date=as.factor(rabund.df$Date)
#rabund.df$Substrate=as.factor(rabund.df$Substrate)
#rabund.df%>%
 # group_by(Substrate,Date)%>%
  #summarise_all(funs(mean,sd))
#taxa=as.vector(colnames(rabund.df[,4:687]))
#names(taxa)=c("taxa")

rabund.h=aggregate(rabund.df[,4:17],list(rabund.df$Date,rabund.df$Substrate),mean)
taxa=list(colnames(rabund.h[,4:16])) 
rabund.h=melt(rabund.h,id.vars=c("Group.1","Group.2"))
ggplot(rabund.h, aes(Group.1,Group.2,fill=value))+geom_tile()+
  facet_grid(variable~Group.2)
  



#rabund.long=melt(rabund.df, id.vars="bacteria.df.6$taxon",variable.name="Sample")
rabund.1=filter(rabund.df, Date==3)
rabund.1$Date=NULL
rabund.1=aggregate(rabund.1[,3:31],list(rabund.1$Substrate),mean)
rabund.1=melt(rabund.1, id="Group.1")
rabund.1$Group.1=as.factor(rabund.1$Group.1)


rabund.2=filter(rabund.df,Date==10)
rabund.2$Date=NULL
rabund.2=aggregate(rabund.2[,3:31],list(rabund.2$Substrate),mean)
rabund.2=melt(rabund.2, id="Group.1")


rabund.3=filter(rabund.df, Date==21)
rabund.3$Date=NULL
rabund.3=aggregate(rabund.3[,3:31],list(rabund.3$Substrate),mean)
rabund.3=melt(rabund.3, id="Group.1")


rabund.4=filter(rabund.df, Date==31)
rabund.4$Date=NULL
rabund.4=aggregate(rabund.4[,3:31],list(rabund.4$Substrate),mean)
rabund.4=melt(rabund.4, id="Group.1")




#select top 10 by substrate
rabund.1.10=rabund.1%>%
  group_by(Group.1)%>%
  arrange(Group.1,desc(value))%>%
  slice(seq(n()*.4))
rabund.1.sigma=dcast(rabund.1.10,Group.1~variable)
rabund.1.sigma=t(rabund.1.sigma)
write.table(rabund.1.sigma,file="170818_rabund.txt",sep="\t")

rabund.2.10=rabund.2%>%
  group_by(Group.1)%>%
  arrange(Group.1,desc(value))%>%
  slice(seq(n()*.4))
rabund.2.sigma=dcast(rabund.2.10,Group.1~variable)
rabund.2.sigma=t(rabund.2.sigma)
write.table(rabund.2.sigma,file="170828_rabund.txt",sep="\t")

rabund.3.10=rabund.3%>%
  group_by(Group.1)%>%
  arrange(Group.1,desc(value))%>%
  slice(seq(n()*.4))
rabund.3.sigma=dcast(rabund.3.10,Group.1~variable)
rabund.3.sigma=t(rabund.3.sigma)
write.table(rabund.3.sigma,file="170905_rabund.txt",sep="\t")

rabund.4.10=rabund.4%>%
  group_by(Group.1)%>%
  arrange(Group.1,desc(value))%>%
  slice(seq(n()*.4))
rabund.4.sigma=dcast(rabund.4.10,Group.1~variable)
rabund.4.sigma=t(rabund.4.sigma)
write.table(rabund.4.sigma,file="170915_rabund.txt",sep="\t")

  


stack.16s.1=ggplot(rabund.1.10, aes(x=Group.1,y=value,group=variable,color=variable,fill=variable))+
  geom_bar(stat="identity",color="black")+
  ggtitle("170818")+
  ylab("Relative Abundance")+
  xlab("Substrate")+
  theme_classic()
stack.16s.1

p=ggplot(rabund.1.10,aes())

stack.16s.2=ggplot(rabund.2.10, aes(x=Group.1,y=value,group=variable,color=variable,fill=variable))+
  geom_bar(stat="identity",color="black")+
  ggtitle("170828")+
  ylab("Relative Abundance")+
  xlab("Substrate")+
  theme_classic()
stack.16s.2
stack.16s.3=ggplot(rabund.3.10, aes(x=Group.1,y=value,group=variable,color=variable,fill=variable))+
  geom_bar(stat="identity",color="black")+
  ggtitle("170905")+
  ylab("Relative Abundance")+
  xlab("Substrate")+
  theme_classic()
stack.16s.3
stack.16s.4=ggplot(rabund.4.10, aes(x=Group.1,y=value,group=variable,color=variable,fill=variable))+
  geom_bar(stat="identity",color="black")+
  ggtitle("170915")+
  ylab("Relative Abundance")+
  xlab("Substrate")+
  theme_classic()
stack.16s.4
ggarrange(stack.16s.1,stack.16s.2,stack.16s.3,stack.16s.4,ncol=2,nrow=2,labels="auto",legend="right", font.label = list(size = 18, color = "black"))
```

```{r}
theme_set(theme_gray(base_size = 12))
algae.df.6=subset.data.frame(algae.df, taxlevel==4,drop=TRUE)
algae.df.6=algae.df.6[,1:71]

sites=list(colnames(algae.df.6[,6:71])) #get list of samples
#total=list(colnames(algae.df.6[,5]))


rabund=function(sites){
  r.abund=sites/algae.df.6$total
  return(r.abund)
}

rabund.23df=rabund(algae.df.6[,6:71])
rabund.23df=cbind(algae.df.6$taxon,rabund.23df)


rabund.23df=melt(rabund.23df,id.vars="algae.df.6$taxon")
rabund.23df=dcast(rabund.23df,variable~algae.df.6$taxon, value.var="value")

#rabund.df$variable=as.numeric(rabund.df$variable)
rabund.23df=separate(rabund.23df,variable,into=c("junk","Date","Substrate"),sep=c(1,7))
rabund.23df=separate(rabund.23df,Substrate,into=c("Substrate","Rep"),sep=c(-1))
rabund.23df$junk=NULL

rabund.23df=droplevels(rabund.23df[-which(rabund.23df$Substrate=='CR'),])
rabund.23df$Date=as.factor(rabund.23df$Date)
rabund.23df$Date=revalue(rabund.23df$Date,c("170818"="3","170828"="10","170905"="21","170915"="31"))
#rabund.df$Date=as.factor(rabund.df$Date)
#rabund.df$Substrate=as.factor(rabund.df$Substrate)
#rabund.df%>%
 # group_by(Substrate,Date)%>%
  #summarise_all(funs(mean,sd))
#taxa=as.vector(colnames(rabund.df[,4:687]))
#names(taxa)=c("taxa")


rabund.23h=aggregate(rabund.23df[,4:70],list(rabund.23df$Date,rabund.23df$Substrate),mean)




 
rabund.23h=melt(rabund.23h,id.vars=c("Group.1","Group.2"))
rabund.23h=rabund.23h%>%
  group_by(Group.1)%>%
  arrange(Group.1,desc(value))%>%
  slice(seq(n()*1))

require(viridis)
ggplot(rabund.23h, aes(Group.1,variable,fill=value))+geom_tile()+
  facet_wrap(~Group.2,nrow=1)+scale_fill_viridis(option="B")+
  theme(#axis.text.x=element_text(angle=90),
        axis.text=element_text(size=10),
        axis.title=element_text(size=10),
        legend.text=element_text(size=10))+
  ylab("Class")+
  xlab("Day of Incubation")
  
```



```{r,include=F}

algae.df.6=subset.data.frame(algae.df, taxlevel==6,drop=TRUE)
drops=c("taxlevel","rankID","daughterlevels","total")
algae.df.6=algae.df.6[,!(names(algae.df.6)%in% drops)]
anosim.df=t(algae.df.6)
anosim.df=as.data.frame(anosim.df)
anosim.df[]=lapply(anosim.df,as.character)
colnames(anosim.df)=anosim.df[1,]
anosim.df=anosim.df[-1,]
anosim.df=anosim.df%>%
  rownames_to_column
anosim.df[,2:240]=lapply(anosim.df[,2:240],function(x) as.numeric(as.character(x)))





anosim.df=separate(anosim.df,rowname,into=c("junk","Date","Substrate"),sep=c(1,7))
anosim.df=separate(anosim.df,Substrate,into=c("Substrate","Rep"),sep=c(-1))
anosim.df$junk=NULL

anosim.df=droplevels(anosim.df[-which(anosim.df$Substrate=='CR'),])
anosim.df$Date=as.factor(anosim.df$Date)
anosim.df$Substrate=as.factor(anosim.df$Substrate)
anosim.df$Date=revalue(anosim.df$Date,c("170818"="3","170828"="10","170905"="21","170915"="31"))


anosim.3=subset(anosim.df, anosim.df$Date=="3")
anosim.10=subset(anosim.df, anosim.df$Date=="10")
anosim.21=subset(anosim.df, anosim.df$Date=="21")
anosim.31=subset(anosim.df, anosim.df$Date=="31")
#anosim.31=anosim.31[,colSums(anosim.31 !=0)>0]



design.df=anosim.df[,1:3]
design.3=anosim.3[,1:3]
design.10=anosim.3[,1:3]
design.21=anosim.3[,1:3]
design.31=anosim.3[,1:3]

anosim.df$Date=NULL
anosim.df$Substrate=NULL
anosim.df$Rep=NULL



anosim.3$Date=NULL
anosim.3$Substrate=NULL
anosim.3$Rep=NULL

anosim.10$Date=NULL
anosim.10$Substrate=NULL
anosim.10$Rep=NULL

anosim.21$Date=NULL
anosim.21$Substrate=NULL
anosim.21$Rep=NULL

anosim.31$Date=NULL
anosim.31$Substrate=NULL
anosim.31$Rep=NULL


#alg.dist=vegdist(anosim.df[,2:240])
#alg.ano=anosim(alg.dist,design.df$Substrate)
#summary(alg.ano)






adonis(anosim.df~Substrate*Date,data=design.df)

pairwise.adonis(anosim.3,factors=design.3$Substrate, 
                sim.method = 'bray', 
                p.adjust.m ='bonferroni')
pairwise.adonis(anosim.10,factors=design.10$Substrate, 
                sim.method = 'bray', 
                p.adjust.m ='bonferroni')
pairwise.adonis(anosim.21,factors=design.21$Substrate, 
                sim.method = 'bray', 
                p.adjust.m ='bonferroni')
pairwise.adonis(anosim.31,factors=design.31$Substrate, 
                sim.method = 'bray', 
                p.adjust.m ='bonferroni')


pairwise.adonis(anosim.df,factors=design.df$Substrate, 
                sim.method = 'bray', 
                p.adjust.m ='bonferroni')
```

```{r Envfit}
env.df<- read.csv("C:/Users/sdunn3/Google Drive/North Branch Chicago Data/NBC/env.df")
env.drops=c("08/15/17","08/22/17","08/25/17","09/01/17","09/08/17","09/12/17")
env.df=droplevels(env.df[!(env.df$Date.Sampled %in% env.drops),])
env.c.drops=c("X","Date.Sampled","Sample","time","doy","width","xdepth","xvelocity",
              "xtemp","xspc","Q")
env.df.fit=env.df[ , !(names(env.df) %in% env.c.drops)]
env.df.fac=env.df %>%
  select(Date.Sampled, Sample)

algae.df.sp=subset.data.frame(algae.df, taxlevel==4,drop=TRUE)

drops <- c("taxlevel","rankID","daughterlevels","total","SDKC1","SDKC2","SDKC3")
algae.df.sp=algae.df.sp[ , !(names(algae.df.sp) %in% drops)]

algae.df.m=melt(algae.df.sp,id.vars="taxon")
algae.df.sp=dcast(algae.df.m,variable~algae.df.sp$taxon)
#rabund.df$variable=as.numeric(rabund.df$variable)
algae.df.sp=separate(algae.df.sp,variable,into=c("junk","Date","Substrate"),sep=c(1,7))
algae.df.sp=separate(algae.df.sp,Substrate,into=c("Substrate","Rep"),sep=c(-1))
algae.df.sp$junk=NULL

algae.df.sp=droplevels(algae.df.sp[-which(algae.df.sp$Substrate=='CR'),])
algae.df.sp$Date=as.factor(algae.df.sp$Date)
algae.df.sp$Date=revalue(algae.df.sp$Date,c("170818"="3","170828"="10","170905"="21","170915"="31"))


algae.df.sps=algae.df.sp[,4:70]
algae.df.sps=algae.df.sps[rowSums(algae.df.sps)!=0,]
#dropping KC results in some rows having zero taxa, remove those rows!

algae.df.env=algae.df.sp[,1:2]

ord.dist=vegdist(algae.df.sps)
ord.nmds=metaMDS(ord.dist)
ORD=data.frame(MDS1=ord.nmds$points[,1],MDS2=ord.nmds$points[,2])
ORD=cbind(ORD,env.df.fac)

fit=envfit(ord.nmds,env.df.fit,perm=999,na.rm=T,display="sites")
fit
fit.df=as.data.frame(fit$vectors$arrows*sqrt(fit$vectors$r))
fit.df$species=rownames(fit.df)
spp.scrs=as.data.frame(scores(fit,display="vectors"))
spp.scrs=cbind(spp.scrs, Species=rownames(spp.scrs),fit$vectors$pvals)
spp.scrs=setnames(spp.scrs, old=("fit$vectors$pvals"), new=c("pvals"))
spp.scrs=spp.scrs[ which (spp.scrs$pvals<0.05),]

 veganCovEllipse<-function (cov, center = c(0, 0), scale = 1, npoints = 100) 
  {
    theta <- (0:npoints) * 2 * pi/npoints
    Circle <- cbind(cos(theta), sin(theta))
    t(center + scale * t(Circle %*% chol(cov)))
 }
df_ell <- data.frame()
  for(g in levels(ORD$Sample)){
    df_ell <- rbind(df_ell, cbind(as.data.frame(with(ORD[ORD$Sample==g,],
                    veganCovEllipse(cov.wt(cbind(MDS1,MDS2),wt=rep(1/length(MDS1),length(MDS1)))$cov,center=c(mean(MDS1),mean(MDS2)))))
                    ,group=g))
  }

ggplot(ORD)+
  geom_point(mapping= aes(MDS1,MDS2,shape=Date.Sampled,color=Sample))+coord_fixed()+
  geom_segment(data=spp.scrs, aes(x=0, xend=spp.scrs$NMDS1/5, y=0,yend=spp.scrs$NMDS2/5),
               arrow=arrow(length=unit(0.1, "cm")),color="red")+
  geom_text(data = spp.scrs, aes(x = NMDS1/5, y = NMDS2/5, label = Species),
            size = 3) +
    geom_path(data=df_ell, aes(x=MDS1, y=MDS2,colour=group), size=1, linetype=2)+ggtitle("Algal Communities")

scores(fit, "vectors")
plot(ord.nmds)
plot(fit, p.max=0.05, col="red")
ord.nmds$stress

```

